#! /usr/bin/env ansible-playbook
# Configure wpa_supplicant role
# Replace 'wifi' with your own inventory group
---
- name: wpa_supplicant | apply role
  hosts: wifi
  roles:
  - role: wpa_supplicant
    tags:
    - wpa_supplicant
    - wifi
